spring:
  profiles:
    active: local

---
  datasource:
    data: classpath:data-h2.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
  spring:
    config:
      activate:
        on-profile: local
---
spring:
  profiles:
    group:
      "prod": set1, realDB
---
server:
  port: 8081
spring:
  config:
    activate:
      on-profile: set1
---
server:
  port: 8082
spring:
  config:
    activate:
      on-profile: set2
