spring:
  profiles:
    active: prod

---
spring:
  profiles: local
  datasource:
    data: classpath:data-h2.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
---
spring:
  profiles:
    group:
      "prod": set1, realDB
---
spring:
  profiles: set1
server:
  port: 8081
---
spring:
  profiles: set2
server:
  port: 8082

